name: deploy-api

on:
  push:
    branches:
      - feature/unit-tests
      - master

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test --reporter verbose
